---
title: "Documentation for AIR"
author: "J Gregg"
date: "06/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Airborne Infection Risk and Covid 19

The Airborne Infection Risk application is designed to give an idea of the risk of contracting SARS-CoV-2 in an enclosed space. It is based on the data in the spreadsheet given at the following link <https://www.unicas.it/siti/laboratori/lami-laboratorio-di-misure-industriali-sezione-meccanica/airborne-infection-risk-calculator.aspx> and relies on the work done by Giorgio Buonanno, Luca Stabile, Lidia Morawska.

The parameters used in the calculation are 

1. Room Area in $m^2$ and Ceiling Height in metres. Used to calculate the volume of the room. Larger rooms allow people to spread out and contain more air, therefore reducing the concentration of virus particles.

2. Number of people and Current Infection Rate per 100,000 people. These numbers are used to assess the likelihood of an infected individual being in the room. The excel spreadsheet on which this projet is based assumes either one or two infected individuals. These numbers try to account for the fact that if the current number of infections in an area is low the risk of becoming infected is reduced.

3. Activity of Participants. There are four options here (Resting, Standing, Light Exercise and Heavy Exercise) and they effect rates of inhalation and exhalation. It is assumed that all participants are performing the same activity and talking at a normal volume as they do it. 
 
4. Length of Activity (in minutes). This information will be used to assess the risk of infection after a set time.

The Risk Plot shows the cumulative risk over eight hours performing an activity under the set parameters. The vertical line is positioned at the length of activity selected.

The Repeated Risk tab assumes that every repetition of an activity is an independent event (this simplification may give overly pessimistic values here). Based on this assumption you can see what your risk of infection is after ten repetitions of an event and how many times you must perform an activity to have a 1% risk of infection. This is designed to highlight that even activities with low individual risk if repeated give a larger cumulative risk over a period of time.




